### ISSUE TITLE
scGPT for CyTOF data

### ISSUE THREAD

**Issue by alex-l-kong** [bowang-lab/scGPT#100]
Can you recommend using scGPT for CyTOF data, either out of the box or through fine tuning? We would like to utilize the scGPT models for cell annotation. Our samples come from bone marrow, brain, breast, and tumor.

**Comment by subercui** [comment]
Hi, I personally don't have much experience with CyTOF data. My understanding is that it typically has much fewer dimensions of protein features, and the magnitude of data values can be quite different from scRNA-seq. So I would recommend you first map the proteins to the gene names in the vocabulary of the pretrained model, and do a full finetuning. I hope the pretrained embeddings and model can help the task. Let me know if these make sense to you
