### ISSUE TITLE
Issue during Step 4: Finetune scGPT with task-specific objectives in Multiomic_Tutorial

### ISSUE THREAD

**Issue by Ragagnin** [bowang-lab/scGPT#104]
Hello, thank you very much for the multiomic tutorial, I was very excited to use it!
However, during the last step, a problem occurred that I was unable to solve, between epoch 5 and epoch 6. Right after the statistics print. From what I researched, it seems that the problem happens when TensorFlow tries to return a type that cannot be converted to a Python type:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-43-fbe1aed4a144>](https://localhost:8080/#) in <cell line: 6>()
     78 
     79         # eval on testdata
---> 80         results = eval_testdata(
     81             model = best_model,
     82             adata_t = adata_sorted if config.per_seq_batch_sample else adata,

13 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/dtypes.py](https://localhost:8080/#) in <module>
     35 from tensorflow.tsl.python.lib.core import pywrap_ml_dtypes
     36 
---> 37 _np_bfloat16 = pywrap_ml_dtypes.bfloat16()
     38 _np_float8_e4m3fn = pywrap_ml_dtypes.float8_e4m3fn()
     39 _np_float8_e5m2 = pywrap_ml_dtypes.float8_e5m2()

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

Has anyone also encountered this error?

Any help would be welcome and thank you in advance!!

**Comment by subercui** [comment]
Hi, it is in between the evaluation function `eval_testdata`. There are 13 frames hidden in your shared message. Could you please share the complete messages printed out?

**Comment by Ragagnin** [comment]
Hello, I managed to identify the error. The problem was related to the versions of numpy and tensorflow. I managed to run the tutorial with tensorflow==2.12.0 and numpy==1.22 versions.
Thanks again for the amazing work.

**Comment by subercui** [comment]
Thank you!
