### ISSUE TITLE
Request for Video Installation Guide for scGPT

### ISSUE THREAD

**Issue by sureshpatel66** [bowang-lab/scGPT#108]
Dear scGPT Contributors,

I would like to extend my gratitude for developing the scGPT framework, which has become an invaluable tool for many of us in the molecular biology field. However, many users, including myself, come from backgrounds where installing complex frameworks can be quite challenging. I have attempted to install scGPT on various platforms, such as Google Cloud and High-Performance Computing servers, but unfortunately, my efforts have not been successful thus far.

Given these difficulties, it would be immensely beneficial if you could provide a step-by-step video tutorial demonstrating the installation process and subsequent usage of scGPT. A visual guide would be an excellent resource for users to refer to and likely reduce the entry barrier for many researchers looking to leverage this powerful tool in their work.

Thank you for considering this request, and I look forward to your positive response.

Best regards,
Suresh

**Comment by docmab23** [comment]
Agreed

**Comment by yh154** [comment]
There's too many issues with installation. A conda requirement file will be very helpful too.

**Comment by subercui** [comment]
Hi, thank you for the question. Based on current feedback and observation, I would say most of the installation issues may be related to flash-attn, such as the comments here #15. Maybe more than 80% of times, the installation of flash-attn has to be resolved case-by-case, regarding users' specific GPU, CUDA versions, or env variable settings. So honestly speaking, I feel either video or conda yaml file may not contribute to the solution for everyone. I've personally shared conda env yaml with a few users, and usually, it still could not solve all the issues with flash-attn and people would go back to the pip installation.

Based on these observations, I am trying to make the flash-attn a really "optional" dependency right now. Hopefully, I can share the updates today, and it should be a better solution for everyone.

In the mean time, if you are looking for a fast workaround. Thanks to @xueerchen1990, who recently created a docker image. while the docker solution is still in test, you may find it at #105 and give it a try.

**Comment by xueerchen1990** [comment]
Please refer to these instructions on setting up the docker container https://github.com/bowang-lab/scGPT/pull/105#issuecomment-1791655120

**Comment by xueerchen1990** [comment]
I also have a blog on installing it using conda https://xueerchen1990.github.io/scgpt/2023/07/24/A-Step-by-Step-Guide-to-install-scGPT.html

**Comment by subercui** [comment]
Hi, I have made flash-attn an optional dependency. Please try to install the new version by `pip install -U scgpt`. Let me know how it works. Also, please find the new instructions for loading the pretrained weights at the beginning of [README](https://github.com/bowang-lab/scGPT/blob/main/README.md), the **2023.11.07** notice.
