### ISSUE TITLE
Expected input / output

### ISSUE THREAD

**Issue by kvittingseerup** [bowang-lab/scGPT#11]
Thanks for an amazing resource - I also believe it will be valuable for the community.

I'm interested in the pre-trained model. Could you elaborate on what is the 

- Expected input to the pre-trained model?
- Expected output to the pre-trained model?

In advance, thanks!

/Kristoffer

**Comment by subercui** [comment]
Thank you. To summarize, the input is mini-batch of tokenized gene expressions per cell. Some input tokens are "unknown genes", where the model is supposed to predict their expression values. These predictions are the output used in pretraining. Please see section 4.3 for details.

**Comment by kvittingseerup** [comment]
Thanks for the quick reply! 

So according to [your script](https://github.com/bowang-lab/scGPT/blob/main/examples/finetune_integration.py), the input is 51 dimensions (`n_bins = 51`)?

But what is the output dimension of the pre-trained model?
