### ISSUE TITLE
Question about comments in databank.py

### ISSUE THREAD

**Issue by ERICMIAO0817** [bowang-lab/scGPT#111]
Hi, thanks for your amazing work!
While reading your code, I have discovered comments contained a link:
[https://github.com/subercui/scGPT-release#the-data-structure-for-large-scale-computing](https://github.com/subercui/scGPT-release#the-data-structure-for-large-scale-computing)
Since I am curious about how to handle large scale data, I clicked the link but found nothing.I wonder if this link leads to a private repo or it's just outdated, therefore brings up this issue.
Thank you in advance for your attention to this. I am looking forward to hearing from you soon.🥺

**Comment by subercui** [comment]
Hi, we tried to write some notes when designing the scBank data structure. The link originally pointed to that. Now, I have put the notes in discussion #112 . Hopefull, it can help further explain the current implementation for you. We proposed some desired features in the notes for handling large single-cell data, and have implemented the core functionalities. We indeed hope to continuously expand the features and also sincerely welcome community efforts.
