### ISSUE TITLE
question on dependencies version

### ISSUE THREAD

**Issue by zackoab** [bowang-lab/scGPT#119]
Hi team,
thanks for your work!
I was trying to use the scGPT package in a different project but issues came up regarding dependencies versioning; I managed to run what I wanted by loosening some restrictions as follow: 

[tool.poetry.dependencies]
python = ">=3.7.13,<3.11"
pandas = ">=1.3.5"
scvi-tools = ">=0.16.0"
llvmlite = ">=0.38.0"
scanpy = "~1.9.1"
torch = ">=1.13.0"
torchtext = ">=0.14.0"
transformers = "^4.18.0"
numba = ">=0.55.1"
scikit-misc = "^0.1.4"
umap-learn = "^0.5.3"
leidenalg = "^0.8.10"
datasets = "^2.3.0"
typing-extensions = "^4.2.0"
scib = "^1.0.3"
cell-gears = "<0.0.3"
orbax = "<0.1.8"

I was wondering if there was any reason for the original restrictions to be strict, or if you could consider loosening them eventually?
I would be happy to make a PR if that could help 
Thanks for your answer

**Comment by subercui** [comment]
Can you let me know which dependency influenced your installation? We previously pinged most of the versions simply around the ones we used during development. So it may likely work with other versions as well

**Comment by zackoab** [comment]
Sure, here are the dependencies on which I had to loosen the restrictions:
pandas
torch 
numba
scvi-tools
llvmlite
torchtext

Thank you

**Comment by subercui** [comment]
Hi, I think a fast but hacky walkaround is to just install these new versions while ignoring the pip warnings. In your virtual env, you may try:
```
pip install scgpt
pip install the new torch and others
```

I will try to relax the dependencies. Currently, I am considering having some recommended versions. For example, recommend the installation of pytorch 1.13.0 by default while allowing installing newer versions. I will look for if pip has any possible solution of this kind, and at least I can add a file with recommended versions. In the meantime, please let me know if you have any suggestion, and feel free to open a PR if you have a solution
