### ISSUE TITLE
Question about input information when integrating multi-omics data

### ISSUE THREAD

**Issue by wang-qf** [bowang-lab/scGPT#12]
hi, i have a question about input model tokens. 
you do the intergration multi-omics task,  whether you concatenate RNA matrix and ATAC matrix, then input to model? and tell embedding which tokens are RNA, which tokens are ATAC?
thanks for your response!

**Comment by subercui** [comment]
Hi, yes, we concatenate the tokens together as the input. For the mosaic integration, we add modality tags in the condition tokens to inform the model whether it is RNA or ATAC. Please see section 4.5 for details

**Comment by wang-qf** [comment]
thanks!

**Comment by krejciadam** [comment]
Hello! 
  Following up on this - would you mind adding an example? It would be very helpful. Thank you!
