### ISSUE TITLE
Bulk RNA-seq for cancer diagnosis

### ISSUE THREAD

**Issue by Hanminghao** [bowang-lab/scGPT#122]
Hello author, this is an excellent work. Do you think it's feasible to fine-tune your single-cell foundational model for cancer diagnosis on Bulk RNA-seq data?

**Comment by subercui** [comment]
Hi, thank you for the question! Yes, I think it is possible to do that and you may try to input each bulk sample to the model and train in a similar fashion. Feel free to let me know if you have any updates or questions

**Comment by Hanminghao** [comment]
Thanks for your reply, I will give it a try as you said!
