### ISSUE TITLE
batch size for pre-training

### ISSUE THREAD

**Issue by yuzhenmao** [bowang-lab/scGPT#124]
Hi, thanks for the amazing work! I found in the original paper, you mentioned the batch size is 32. May I ask if this is the whole batch size or the batch size per GPU? And how many GPUs did you use during pretraining? Thanks!

**Comment by yuzhenmao** [comment]
I notice that in https://github.com/bowang-lab/scGPT/issues/5, you used 4 A100 to fit 10.3M cells for 3 days, which means for one epoch, it takes around 12 hours. So it seems that the batch size is 32 per GPU, and in total is 128; or the total batch size is even larger? Please correct me if I am wrong. Thank you very much!

**Comment by subercui** [comment]
Hi, thank you for the question. Yes, that stands for the batch size per GPU. When we trained the recent model on the 33.3M cells, we used more GPUs, 16 A100 in total. So the total batch size is equally 512.
