### ISSUE TITLE
Direction of Perturbation ?

### ISSUE THREAD

**Issue by docmab23** [bowang-lab/scGPT#126]
While using Perturbation prediction, how can we define the direction of perturbation (upregulated, downregulated or knockout), I tried to find the answer in the GEARs paper. Does it depend on what kind of dataset, the model was trained on, for example whether it was CRISPRa or CRISPRi , etc ?

**Comment by subercui** [comment]
Hi, thanks for the question. (1) If you are asking about the direction of the exact gene being perturbed, that can be informed by the type of experiment. For example, as you mentioned, CRISPRa should increase the expression and conversely for CRISPi. (2) Model predicts the expression of genes post perturbation, so one can examine the expression in control and after perturbation to see whether it is upregulated or the other direction. (3) If your question is about how to fine-tune on a dataset with more than one direction, for example, a dataset with both CRISPRa and CRISPRi experiments. Currently we did not show that, but I think this can be trained by setting multiple perturbation flags as input tokens for the experiments, and the model can thus learn the difference between them.

**Comment by docmab23** [comment]
Thank you so much, that's exactly what I was expecting. Using flags for CRISPRa , CRISPRi , etc. as input tokens seems like a good idea.
