### ISSUE TITLE
Value binning for reference mapping. 

### ISSUE THREAD

**Issue by mksingh2104** [bowang-lab/scGPT#128]
Hi there,

I have a question. I can see value binning is consistently used for fine-tuning tasks (and rational for this is written in the paper), however, I don't see value binning on input data in reference mapping tutorial. I will really appreciate more insight into it. 

Sincerely,
Manoj

**Comment by subercui** [comment]
Hi, thank you for the question and yes, the binning is consistently used for most of the tasks. For the reference mapping tutorial, the binning is conducted in a more efficient way in the data collator. Specifically, you can find this new implementation in the `embed_data` function in [cell_emb.py](https://github.com/bowang-lab/scGPT/blob/main/scgpt/tasks/cell_emb.py). The call is around these lines https://github.com/bowang-lab/scGPT/blob/418b0f623fb1f17641a12c9e50f72f4419311745/scgpt/tasks/cell_emb.py#L96-L105
