### ISSUE TITLE
Value binning in perturbation tutorial

### ISSUE THREAD

**Issue by alexaibio** [bowang-lab/scGPT#144]
Hello, 
first of all, thank for this excellent work!
I am exploring the perturbation example and I have difficulties finding a value binning during perturbation prediction... for me it seems like you train and fine tune model with binned values but them predict on raw expression data, without binning. 
Please advice... 

def predict:
https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Perturbation.ipynb

Thank you
Alex

**Comment by subercui** [comment]
Hi, thank you for the question. Your understanding is correct. We used the real values instead of binning in consideration that the actual absolute post-perturbation expression values are important and to be predicted in the task. We also stated this choice in section 4.5 of our online manuscript
