### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ceferisbarov** [bowang-lab/scGPT#154]
`pip install scgpt "flash-attn<1.0.5"` gives the following error:
```
ERROR: Cannot install scgpt==0.1.3 and scgpt==0.1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    scgpt 0.1.5 depends on llvmlite<0.39.0 and >=0.38.0
    scgpt 0.1.3 depends on llvmlite<0.39.0 and >=0.38.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
I don't understand why pip is trying to install two versions.

I also had to install `wheel` and `packaging` packages before this, but I am not sure if that's relevant.

**Comment by kocemir** [comment]
**I can tell what I have done to able to run at least annotation and integration notebooks successfully.**

I am running experiments on  a server:  **Driver Version: 525.60.13    CUDA Version: 12.0**  

conda create --name scgpt_ann python=3.10 r-base r-devtools
conda activate scgpt_ann
pip install scgpt
pip install ipython   ( you can run without this, if you encounter a problem related to ipython, then install it, very trivial error)

Finally, using pip, install all the packages in develeopment section(in pyproject.toml in repo) too. (I am not sure if it is necessary or not, but in this form it works.)
After that, everything worked well for me.

In integration task, if your numpy is above 1.20.0, you will probably encounter the problem like np.str, np.bool. To solve this error, go to the scvi dataset creation module, replace np.str and np.bool with str and bool.

**Comment by subercui** [comment]
@ceferisbarov , I haven't seen the error message before. Could you also let me know what is the python can cuda versions you are using?

Thanks @kocemir for the help!

**Comment by warming151** [comment]
> **I can tell what I have done to able to run at least annotation and integration notebooks successfully.**
> 
> I am running experiments on a server: **Driver Version: 525.60.13 CUDA Version: 12.0**
> 
> conda create --name scgpt_ann python=3.10 r-base r-devtools conda activate scgpt_ann pip install scgpt pip install ipython ( you can run without this, if you encounter a problem related to ipython, then install it, very trivial error)
> 
> Finally, using pip, install all the packages in develeopment section(in pyproject.toml in repo) too. (I am not sure if it is necessary or not, but in this form it works.) After that, everything worked well for me.
> 
> **Additionally, if you would like to work with fast-attn, then follow this:**
> 
> pip install packaging pip install flash-attn==1.0.4 (if your driver is old, probably it will not install)
> 
> In integration task, if your numpy is above 1.20.0, you will probably encounter the problem like np.str, np.bool. To solve this error, go to the scvi dataset creation module, replace np.str and np.bool with str and bool.

Thank you for the sharing! I wonder whether it would be OK if I don't install flash-attn. Is it necessary?  Thanks!

**Comment by kocemir** [comment]
@warming151  sorry for the too late reply. Yes, flash-attn is optional. If you dive into the model file ( that transformer is built and called), you can see that if your environment does not contain flash-attn, then the code will direct you to the standard TransformerEncoder. So, you do not need flash-attn.

**Comment by subercui** [comment]
Thanks for the help! Yes, the flash-attn dependency is optional now
