### ISSUE TITLE
Fewer genes but longer zero-shot runtime: what's happening?

### ISSUE THREAD

**Issue by chartl** [bowang-lab/scGPT#155]
I'm seeking to compare three scGPT embeddings:

1: all genes (n_hvg=False) zero-shot

2: top genes (n_hvg=3000) zero-shot

3: top genes (n_hvg=3000) fine-tuned

For 1 and 2, the only difference is the argument to the Preprocessor class, and the shape of the resulting adata.

However, for (1), when calling `.encode_batch`, the model runs at ~275 it/s; but for (2), which is simply a narrower dataset, the encoding pass runs at ~5 it/s (55x slower!).  I call `model.to(device)` before (1) but not a second time prior to (2). Why is the encoding slower on a narrower dataset?

**Comment by subercui** [comment]
Thank you for the interesting question. As you suggested, can you double check the device when running in the second option, the speed feels like running on CPU. Also, you can specify the device here in the function call https://github.com/bowang-lab/scGPT/blob/706526a76d547de4ed711fa028c99be5bdf6ad8a/scgpt/tasks/cell_emb.py#L155
