### ISSUE TITLE
a query about uniform distribution in binning

### ISSUE THREAD

**Issue by WT215** [bowang-lab/scGPT#157]
Hello,

Thank you for this very nice work!

Just out of curiousity, may I ask what is the purpose for the code in the function [_digitize](https://github.com/bowang-lab/scGPT/blob/706526a76d547de4ed711fa028c99be5bdf6ad8a/scgpt/preprocess.py#L267)

It states "This method spreads data uniformly when bins have same values." Is it a heuristic way to handle the binning or does any other study handle binning in this way?

Many thanks!

**Comment by subercui** [comment]
Hi, I think to our best knowledge, this is a newly introduced way of binning and we found it useful for pretraining. The idea can be connected to the quatile normalization , which has been used for RNA-seq data, https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02078-0
