### ISSUE TITLE
Saving output as Anndata object

### ISSUE THREAD

**Issue by giuliaelgarcia** [bowang-lab/scGPT#159]
I am running scGPT for the first time and was wondering if it is possible to save the relevant outputs in an Anndata object or append them to an existing Anndata object for downstream analysis and comparisons. If so, what would be the best way to go about this? Thank you!

**Comment by subercui** [comment]
Yes, you can always save the output in anndata. You may save the cell embeddings in `adata.obsm` easily, https://github.com/bowang-lab/scGPT/blob/706526a76d547de4ed711fa028c99be5bdf6ad8a/scgpt/tasks/cell_emb.py#L148-L159, by default it saves the embedding to a new obsm "X_scGPT" in the input anndata. You can also return a new anndata by passing the argument `return_new_adata=True`

This feature is exemplified in this tutorial https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Reference_Mapping.ipynb
![image](https://github.com/bowang-lab/scGPT/assets/11674033/cbcf88c8-9364-418e-b7be-70f6d339a408)


For fine-tuning tasks, you may want to save the model's predictions, such as cell type labels in https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Annotation.ipynb. It can be saved as here:

![image](https://github.com/bowang-lab/scGPT/assets/11674033/2f1a58aa-bb35-49d9-9889-59a6e6826eb2)
