### ISSUE TITLE
HVG_FLAVOR parameter in Cell Type Annotation

### ISSUE THREAD

**Issue by yueming-ding** [bowang-lab/scGPT#166]
@subercui I didn't fully understand the parameter and logic of HVG_FLAVOR in Cell Type Annotation. What is the parameter for? I noticed that there are two values for this parameter: seurat_v3 and cell_ranger. How could I choose the value (seurat_v3 or cell_ranger) for my cell type annotation? Does this parameter affect what kinds of HVG selected if I select seurat_v3 or cell_ranger?

**Comment by subercui** [comment]
Hi, thank you for the question. The preprocessor calls the scanpy functions internally, as indicated in the [docstring](https://github.com/bowang-lab/scGPT/blob/706526a76d547de4ed711fa028c99be5bdf6ad8a/scgpt/preprocess.py#L61). So this hvg_flavor has the same meaning as detailed [here](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.highly_variable_genes.html). To summarize, this is a user setting and you may use a flavor that suits your specific data. For example, the seurat_v3 flavor assumes raw data counts and is a more recent method, and the cell_ranger flavor assumes log transformed data.

**Comment by yueming-ding** [comment]
Thanks @subercui!
