### ISSUE TITLE
max_length and cell number 

### ISSUE THREAD

**Issue by giuliaelgarcia** [bowang-lab/scGPT#184]
Hi, I am currently running scGPT and was wondering what exactly the `max_length` and `max_seq_length` stand for. Is it the amount of cells that is in the input data or something else? 
Because no matter what I change when running the model it tends to pick up way less cells than whats in my input. 
Thank you in advance!!

**Comment by subercui** [comment]
Hi, which tutorial or application are you running and can you share more code or print out messages? In a word, the max_length sets the max number of input tokens to the transformer model, it should have no influence on the number of cells. Also in all tutorials, the model takes in cells in minibatch mode. For example, if the batch size is set to 64, that means, each time the model takes in 64 cells out of the total N cells you provided in the data, and it will loop over all N cells in N/64 iterations.

**Comment by giuliaelgarcia** [comment]
Hi thank you for your quick reply. So I'm not meant to specify anywhere the amount of cells in my object? 
I am running the zero-shot tutorial!

**Comment by subercui** [comment]
Indeed, you don't need to specify the amount of cells. In the zero-shot tutorial, there is a step calling this `embed_data` function. Here, https://github.com/bowang-lab/scGPT/blob/706526a76d547de4ed711fa028c99be5bdf6ad8a/scgpt/tasks/cell_emb.py#L163 , the function assumes the first input argument is the anndata object containing the sequencing data at `adata.X`. It should process all cells and output the results in a new anndata or to `adata.obsm["X_scGPT"]`. See these lines https://github.com/bowang-lab/scGPT/blob/706526a76d547de4ed711fa028c99be5bdf6ad8a/scgpt/tasks/cell_emb.py#L275-L279

**Comment by subercui** [comment]
So you may look at the size of your input data, if you still find the size does not match, please feel free to share more info about the code and data you are using.
