### ISSUE TITLE
max_seq_len in perturbation prediction analysis

### ISSUE THREAD

**Issue by ChloeYou8** [bowang-lab/scGPT#189]
Hi, thanks for providing such a good model to use.
I have a question about the max_seq_len.  Based on the code to fine-tune the model, if I have genes more than the value you provide is 1536, then they are sampled to be used. How is this value selected? And what if the perturbation gene is not included?
<img width="683" alt="image" src="https://github.com/bowang-lab/scGPT/assets/164972706/2e6fc1b7-cc6a-4042-bfa1-05511b286e2e">
Cheers,
Yue

**Comment by subercui** [comment]
Hi, thank you for the great question. First, we tried to have a rather large max length while using reasonable GPU memory, so 1536 is used. It is simply a nice large number as 2^10 + 2^9. For the second question, we had some internal experiments with different max length. When comparing setting it to the full length of the input data or 1536, the training performance is similar to each other. Now, rethinking about the question you asked about the case perturbed gene not selected in some iterations, admittedly it may introduce some noise during the training while just empirically, the training still worked out fine. I do think it is a good suggestion, we would like to update the code soon. By the way, the actual inference after training will always use all genes in the tutorial.

**Comment by subercui** [comment]
Going to close the issue. Feel free to reopen if you have further questions.
