### ISSUE TITLE
Questions about cell type annotation

### ISSUE THREAD

**Issue by QiaolinLu** [bowang-lab/scGPT#19]
Hi, Thanks for your great work. I want to use scGPT to do cell type annotation task on my own dataset. Is there any demo code about how to do this task? Thanks

**Comment by subercui** [comment]
Yes, we are working on wrapping it up and will release notebooks for cell type annotation and other tasks soon in the next week.

**Comment by QiaolinLu** [comment]
Thanks

**Comment by KatarinaYuan** [comment]
Hi, wondering any follow-ups on this issue? Thank you for the great work. It would be great to see the release of downstream tasks!

**Comment by subercui** [comment]
Hi @KatarinaYuan , the cell type annotation tutorial has already been released. Please find it in the tutorial folder and [here](https://scgpt.readthedocs.io/en/latest/tutorial_annotation.html).
