### ISSUE TITLE
ASAP PBMC dataset, how to fine-tune?

### ISSUE THREAD

**Issue by LiXiaoli921** [bowang-lab/scGPT#190]
hi, how to use your code for the ASAP PBMC mosaic integration task? Thanks for your help. 

As the file [scGPT](https://github.com/bowang-lab/scGPT/tree/main)/[examples](https://github.com/bowang-lab/scGPT/tree/main/examples)
/**finetune_integration.py**
which only used the function to load data with `# ## Loading and preparing data
if dataset_name == "PBMC_10K":
    adata = scvi.data.pbmc_dataset()  # 11990 × 3346
    ori_batch_col = "batch"
    adata.obs["celltype"] = adata.obs["str_labels"].astype("category")
    adata.var = adata.var.set_index("gene_symbols")
    data_is_raw = True`
could you please show the cod of how you fine-tune on the mosaic ASAP PBMC dataset?

**Comment by subercui** [comment]
Going to close the issue. Feel free to reopen if you have further questions.

**Comment by LiXiaoli921** [comment]
thanks so much
