### ISSUE TITLE
Hardware used for pre-training

### ISSUE THREAD

**Issue by pfgherardini** [bowang-lab/scGPT#193]
Hi,

Congratulations on this great project! Can you give an idea of the amount of compute (hardware and training time) that was used for pre-training the model? I looked for this info in the publication but couldn't find it.

Thank you!

**Comment by subercui** [comment]
Hi, thank you for the question. When we trained the main human model last year, we used 16 A100 GPUs for around 6 days, that is for 6-epoch training.

**Comment by subercui** [comment]
Going to close the issue. Feel free to reopen if you have further questions.
