### ISSUE TITLE
Which datasets were trained on?

### ISSUE THREAD

**Issue by Yanay1** [bowang-lab/scGPT#2]
Hello,

Would it be possible to have a list of the datasets that were trained on?

Thanks!

**Comment by subercui** [comment]
Please see section 4.6 in our manuscript https://www.biorxiv.org/content/10.1101/2023.04.30.538439 for the datasets we used. If you are interested in the pretraining datasets, we filtered and manually downloaded them from the cellxgene portal. The first paragraph in section 4.6 describes this process.

For legal reasons, we don't release the pretraining datasets for now. However, I think you can follow the same process to download a similar collection of data from the cellxgene portal. Note that we downloaded the data last year, so the exact collection after filtering may vary a bit now on the portal website.

**Comment by subercui** [comment]
Close the issue for now. Let me know if this is any further questions or comments

**Comment by Hrovatin** [comment]
Hi,
I was wondering what was the reason for focusing so strongly on immune/PBMC datasets for pre-training if this is supposed to be a model that generalizes well across datasets.
