### ISSUE TITLE
Size of the whole human dataset

### ISSUE THREAD

**Issue by NozomiMizore** [bowang-lab/scGPT#212]
Thanks for ur great work! The paper and docs have mentioned that the whole-human dataset consists of 33M cell 's data.  And u have given some shell scripts to crawl the  data from CellxGene. Actually, I want to know the size of whole-human dataset. How many TBs？

**Comment by subercui** [comment]
Hi, I think the raw data in anndata h5ad format is around 700GB. If you crawl the data recently, the size can get larger since the update on CELLxGENE.
