### ISSUE TITLE
CellxGene configure version issue in the current repo

### ISSUE THREAD

**Issue by YubinXie** [bowang-lab/scGPT#233]
In the repo data_config.py it says VERSION = "2023-05-08". But there is so such version in cellxgene and in the scGPT paper, the version used is "2023-05-15"

**Comment by subercui** [comment]
Hi, appologize for the confusion. Long story short, the version in the readme and data_config may be the more accurate info. When we trained the model in 2023, there was indeed a release version of CellxGene of 05-08. However, it was no longer on their website when we later checked the release info, and most likely they just renewed their release plans and removed legacy versions. The most similar version around the date is the LTS release 05-15, which we assumed likely containing the same data.

Nevertheless, if you want to play around pretraining data from cellxgene, I will highly recommend using the latest release. We also mentioned this suggestion here https://github.com/bowang-lab/scGPT/blob/main/data/cellxgene/README.md?plain=1#L21. You can find all their LTS releases here https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_data_release_info.html

**Comment by YubinXie** [comment]
@subercui Thank you so much for the detailed reply. it is very helpful.
The 2023-05-15 release indeed has similar number of cells as you recorded in readme.
When I used latest, it only gives me 80% amount cells comparing to 2023-05-15 - which is really weird. I will check with cellxgene on this - if you know anything about the difference, let me know! Thanks.
