### ISSUE TITLE
`layer_data.A` in `preprocess.y`

### ISSUE THREAD

**Issue by sklarz-bgu** [bowang-lab/scGPT#254]
Hi. When running `preprocess.py`, I get the following error:

`AttributeError: 'csr_matrix' object has no attribute 'A'`

I'm running `preprocess()` as part of the tutorial described [here](https://scgpt.readthedocs.io/en/latest/tutorial_grn.html#1.2-Load-dataset-of-interest)

offending lines: 181-182.

```
layer_data = _get_obs_rep(adata, layer=key_to_process)
layer_data = layer_data.A if issparse(layer_data) else layer_data
``` 
`type(layer_data)` is `scipy.sparse._csr.csr_matrix`, `issparse(layer_data)` is `True`.
 
Could this be an issue of versions? I think I installed everything correctly.

Thanks
Menachem

**Comment by 8gabri8** [comment]
Same problem.

**Comment by sklarz-bgu** [comment]
You can do the following modification and it seems to work fine:

```
layer_data = layer_data.toarray() if issparse(layer_data) else layer_data
```

Hope it does what it's supposed to do...

**Comment by subercui** [comment]
Thank you @sklarz-bgu for providing the solution. I think that's some api mismatch bettween dependency versions. That solution does what it intended to do.
