### ISSUE TITLE
`tutorials/Tutorial_Perturbation.ipynb` - `pert_pad_id` is set to 0

### ISSUE THREAD

**Issue by qianachen** [bowang-lab/scGPT#266]
In `scgpt/model/generation_model.py`, the `pert_pad_id` is used as the `padding_idx` for pert_encoder, i.e.,
```python
self.pert_encoder = nn.Embedding(3, d_model, padding_idx=pert_pad_id)
``` 
However, the `pert_encoder` encodes `pert_flags`, which represents gene perturbation with values 0 and 1. Could you clarify if setting `pert_pad_id` to 0 in ` tutorials/Tutorial_Perturbation.ipynb` is a deliberate design choice? Does this mean that only the embedding vectors corresponding to perturbed genes (with `pert_flags` set to 1) are involved in training for pert_encoder, while those corresponding to `pert_flags` set to 0 are ignored due to `padding_idx`?

**Comment by subercui** [comment]
Thank you for the question! Yes, that is a designed choice. We had a small trick here to ignore the pert_pad_id, and by default in pytorch "the embedding vector at padding_idx will default to all zeros", https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html
