### ISSUE TITLE
scb

### ISSUE THREAD

**Issue by wenhao2024** [bowang-lab/scGPT#267]
Hello：
I want to transfer my h5ad to scb,but when i run it
I meet some problem in the script of gene_tokenizer.py
what the definition of insert_token ？ 
And When I run _vocab = cls([]) inside from_dict, the program just hangs at this step without proceeding further. There are no errors reported either.

**Comment by subercui** [comment]
Hi, thanks for the question. So that sinlge line just creates an instance of the `GeneVocab` class. Could you try `vocab = GeneVocab([])` and share the error message?
