### ISSUE TITLE
Data preprocessing for perturbation

### ISSUE THREAD

**Issue by BoAtNY** [bowang-lab/scGPT#271]
Hi,

Thanks for your work!

I'm trying to run single and double perturbation predictions on another dataset. As we use PertData to load datasets, I preprocessed the dataset with PertData.new_data_process(), which gave me cell_graphs.pkl and perturb_processed,h5ad. when I start training, I get an error because pert_flags = x[:, 1].long().view(batch_size, n_genes) seems to be missing in the processed dataset. Am I missing anything when preprocessing it? Any guidance would be greatly appreciated!

**Comment by subercui** [comment]
Hi, please see #36 and let me know if you still have further questions.

**Comment by BoAtNY** [comment]
Thanks for your response! But it still didn't work with GEARS version 0.0.1. There's a function yielding IndexError: index 0 is out of bounds for axis 0 with size 0.
def get_pert_idx(self, pert_category, adata_):
        pert_idx = [np.where(p == self.gene_names)[0][0]
                    for p in pert_category.split('+')
                    if p != 'ctrl']
        return pert_idx
        
I think this is because no perturbation is in the gene_name in my dataset. Do I need a dataset that includes the expressions of perturbations?
