### ISSUE TITLE
All packages in conda environment but could not access it 

### ISSUE THREAD

**Issue by mahlaranjeet** [bowang-lab/scGPT#29]
INSTALLED PACKAGES
(scGPT_new) rmahla_admin@kirmac201 ~ % conda list
# packages in environment at /Applications/anaconda3/envs/scGPT_new:
#
# Name                    Version                   Build  Channel
aiofiles                  22.1.0           py39hecd8cb5_0  
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aiosqlite                 0.18.0           py39hecd8cb5_0  
airr                      1.3.1                    pypi_0    pypi
anndata                   0.9.1              pyhd8ed1ab_0    conda-forge
anyio                     3.5.0            py39hecd8cb5_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
appnope                   0.1.2           py39hecd8cb5_1001  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39hca72f7f_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0           py39hecd8cb5_0  
babel                     2.11.0           py39hecd8cb5_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.12.2           py39hecd8cb5_0  
biopython                 1.77                     pypi_0    pypi
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
bottleneck                1.3.5            py39h67323c0_0  
brotli                    1.0.9                hca72f7f_7  
brotli-bin                1.0.9                hca72f7f_7  
brotlipy                  0.7.0           py39h9ed2024_1003  
ca-certificates           2023.05.30           hecd8cb5_0  
certifi                   2023.5.7         py39hecd8cb5_0  
cffi                      1.15.1           py39h6c40b1e_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
comm                      0.1.2            py39hecd8cb5_0  
contourpy                 1.0.5            py39haf03e11_0  
cryptography              39.0.1           py39hf6deb26_2  
cycler                    0.11.0             pyhd3eb1b0_0  
datasets                  2.13.1                   pypi_0    pypi
debugpy                   1.5.1            py39he9d5cce_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.14                   pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
dnspython                 2.3.0                    pypi_0    pypi
entrypoints               0.4              py39hecd8cb5_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.12.2                   pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               hd8bbffd_0  
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gettext                   0.21.0               he85b6c0_1  
giflib                    5.2.1                h6c40b1e_3  
glib                      2.69.1               hfff2838_2  
gseapy                    1.0.5                    pypi_0    pypi
gst-plugins-base          1.14.1               hcec6c5f_1  
gstreamer                 1.14.1               h6c40b1e_1  
h5py                      3.9.0                    pypi_0    pypi
hdf5                      1.10.6               h10fe05b_1  
huggingface-hub           0.16.2                   pypi_0    pypi
hyperopt                  0.1.2                    pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      3.4              py39hecd8cb5_0  
igraph                    0.10.5                   pypi_0    pypi
importlib-metadata        6.0.0            py39hecd8cb5_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
intel-openmp              2023.1.0         ha357a0b_43547  
ipykernel                 6.19.2           py39h01d92e1_0  
ipython                   8.12.0           py39hecd8cb5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                8.0.4            py39hecd8cb5_0  
jedi                      0.18.1           py39hecd8cb5_1  
jinja2                    3.1.2            py39hecd8cb5_0  
joblib                    1.2.0            py39hecd8cb5_0  
jpeg                      9e                   h6c40b1e_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.17.3           py39hecd8cb5_0  
jupyter                   1.0.0            py39hecd8cb5_8  
jupyter_client            8.1.0            py39hecd8cb5_0  
jupyter_console           6.6.3            py39hecd8cb5_0  
jupyter_core              5.3.0            py39hecd8cb5_0  
jupyter_events            0.6.3            py39hecd8cb5_0  
jupyter_server            2.5.0            py39hecd8cb5_0  
jupyter_server_fileid     0.9.0            py39hecd8cb5_0  
jupyter_server_terminals  0.4.4            py39hecd8cb5_1  
jupyter_server_ydoc       0.8.0            py39hecd8cb5_1  
jupyter_ydoc              0.2.4            py39hecd8cb5_0  
jupyterlab                3.6.3            py39hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.22.0           py39hecd8cb5_0  
jupyterlab_widgets        3.0.5            py39hecd8cb5_0  
kiwisolver                1.4.4            py39hcec6c5f_0  
krb5                      1.20.1               h428f121_1  
lcms2                     2.12                 hf1fd2bf_0  
leidenalg                 0.10.0                   pypi_0    pypi
lerc                      3.0                  he9d5cce_0  
libbrotlicommon           1.0.9                hca72f7f_7  
libbrotlidec              1.0.9                hca72f7f_7  
libbrotlienc              1.0.9                hca72f7f_7  
libclang                  12.0.0          default_hbc2896b_2  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.17                 hb664fd8_0  
libedit                   3.1.20221030         h6c40b1e_0  
libffi                    3.4.4                hecd8cb5_0  
libgfortran               5.0.0           11_3_0_hecd8cb5_28  
libgfortran5              11.3.0              h9dfd629_28  
libiconv                  1.16                 hca72f7f_2  
libllvm12                 12.0.0               h9b2ccf5_3  
libllvm14                 14.0.6               h91fad77_3  
libpng                    1.6.39               h6c40b1e_0  
libpq                     12.15                h04015c4_1  
libsodium                 1.0.18               h1de35cc_0  
libtiff                   4.5.0                hcec6c5f_2  
libwebp                   1.2.4                hf6ce154_1  
libwebp-base              1.2.4                h6c40b1e_1  
libxml2                   2.10.3               h930c0e2_0  
libxslt                   1.1.37               h6d1eb0e_0  
llvm-openmp               14.0.6               h0dcd299_0  
llvmlite                  0.40.0           py39hfff2838_0  
lxml                      4.9.2            py39h6c40b1e_0  
lz4-c                     1.9.4                hcec6c5f_0  
markupsafe                2.1.3                    pypi_0    pypi
matplotlib-base           3.7.1            py39hda11e5a_1  
matplotlib-inline         0.1.6            py39hecd8cb5_0  
mistune                   0.8.4           py39h9ed2024_1000  
mkl                       2023.1.0         h59209a4_43558  
mkl-service               2.4.0            py39h6c40b1e_1  
mkl_fft                   1.3.6            py39h07fba90_1  
mkl_random                1.2.2            py39h07fba90_1  
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
munkres                   1.1.4                      py_0  
natsort                   7.1.1              pyhd3eb1b0_0  
nbclassic                 0.5.5            py39hecd8cb5_0  
nbclient                  0.5.13           py39hecd8cb5_0  
nbconvert                 6.5.4            py39hecd8cb5_0  
nbformat                  5.7.0            py39hecd8cb5_0  
ncurses                   6.4                  hcec6c5f_0  
nest-asyncio              1.5.6            py39hecd8cb5_0  
networkx                  2.8.4            py39hecd8cb5_1  
notebook                  6.5.4            py39hecd8cb5_0  
notebook-shim             0.2.2            py39hecd8cb5_0  
nspr                      4.35                 hcec6c5f_0  
nss                       3.89.1               hcec6c5f_0  
numba                     0.57.0           py39h3ea8b11_0  
numexpr                   2.8.4            py39h47b59a4_1  
numpy                     1.25.0                   pypi_0    pypi
numpy-base                1.24.3           py39hcfaf2c3_1  
openssl                   3.0.9                hca72f7f_0  
packaging                 23.0             py39hecd8cb5_0  
pandas                    2.0.3                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
patsy                     0.5.3            py39hecd8cb5_0  
pcre                      8.45                 h23ab428_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0            py39hcec6c5f_0  
pip                       23.1.2           py39hecd8cb5_0  
platformdirs              2.5.2            py39hecd8cb5_0  
ply                       3.11             py39hecd8cb5_0  
pooch                     1.4.0              pyhd3eb1b0_0  
presto                    0.7.0                    pypi_0    pypi
prometheus_client         0.14.1           py39hecd8cb5_0  
prompt-toolkit            3.0.36           py39hecd8cb5_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
psutil                    5.9.0            py39hca72f7f_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   12.0.1                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydot                     1.4.2                    pypi_0    pypi
pygments                  2.15.1           py39hecd8cb5_1  
pymongo                   4.4.0                    pypi_0    pypi
pynndescent               0.5.10           py39hecd8cb5_0  
pyopenssl                 23.0.0           py39hecd8cb5_0  
pyparsing                 3.0.9            py39hecd8cb5_0  
pyqt                      5.15.7           py39he9d5cce_0  
pyqt5-sip                 12.11.0          py39he9d5cce_0  
pyrsistent                0.18.0           py39hca72f7f_0  
pysocks                   1.7.1            py39hecd8cb5_0  
python                    3.9.16               h5ee71fb_3  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py39hecd8cb5_0  
python-json-logger        2.0.7            py39hecd8cb5_0  
pytz                      2022.7           py39hecd8cb5_0  
pyyaml                    6.0              py39h6c40b1e_1  
pyzmq                     25.1.0           py39hcec6c5f_0  
qt-main                   5.15.2               h719ae48_7  
qt-webengine              5.15.9               h90a370e_4  
qtconsole                 5.4.2            py39hecd8cb5_0  
qtpy                      2.2.0            py39hecd8cb5_0  
qtwebkit                  5.212                hbfab81c_5  
readline                  8.2                  hca72f7f_0  
regex                     2023.6.3                 pypi_0    pypi
requests                  2.29.0           py39hecd8cb5_0  
rfc3339-validator         0.1.4            py39hecd8cb5_0  
rfc3986-validator         0.1.1            py39hecd8cb5_0  
safetensors               0.3.1                    pypi_0    pypi
scanpy                    1.9.3              pyhd8ed1ab_0    conda-forge
scgpt                     0.1.2.post1              pypi_0    pypi
scib                      1.1.3                    pypi_0    pypi
scikit-learn              1.2.2            py39hcec6c5f_0  
scikit-misc               0.2.0                    pypi_0    pypi
scipy                     1.11.1                   pypi_0    pypi
scvi                      0.6.8                    pypi_0    pypi
seaborn                   0.12.2           py39hecd8cb5_0  
send2trash                1.8.0              pyhd3eb1b0_1  
session-info              1.0.0              pyhd8ed1ab_0    conda-forge
setuptools                67.8.0           py39hecd8cb5_0  
sip                       6.6.2            py39he9d5cce_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py39hecd8cb5_1  
soupsieve                 2.4              py39hecd8cb5_0  
sqlite                    3.41.2               h6c40b1e_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.13.5           py39hacda100_1  
stdlib-list               0.8.0            py39hecd8cb5_0  
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             ha357a0b_0  
terminado                 0.17.1           py39hecd8cb5_0  
texttable                 1.6.7                    pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0  
tinycss2                  1.2.1            py39hecd8cb5_0  
tk                        8.6.12               h5d9f67b_0  
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1            py39hecd8cb5_0  
torch                     2.0.1                    pypi_0    pypi
torchdata                 0.6.1                    pypi_0    pypi
torchtext                 0.15.2                   pypi_0    pypi
tornado                   6.2              py39hca72f7f_0  
tqdm                      4.65.0           py39h01d92e1_0  
traitlets                 5.7.1            py39hecd8cb5_0  
transformers              4.30.2                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing_extensions         4.6.3            py39hecd8cb5_0  
tzdata                    2023c                h04d1e81_0  
umap-learn                0.5.3            py39hecd8cb5_0  
urllib3                   1.26.16          py39hecd8cb5_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39hecd8cb5_1  
websocket-client          0.58.0           py39hecd8cb5_4  
wheel                     0.38.4           py39hecd8cb5_0  
widgetsnbextension        4.0.5            py39hecd8cb5_0  
wrapt                     1.15.0                   pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h6c40b1e_0  
y-py                      0.5.9            py39h7242b5c_0  
yaml                      0.2.5                haf1e3a3_0  
yamlordereddictloader     0.4.0                    pypi_0    pypi
yarl                      1.9.2                    pypi_0    pypi
ypy-websocket             0.8.2            py39hecd8cb5_0  
zeromq                    4.3.4                h23ab428_0  
zipp                      3.11.0           py39hecd8cb5_0  
zlib                      1.2.13               h4dc903c_0  
zstd                      1.5.5                hc035e20_0  
(scGPT_new) rmahla_admin@kirmac201 ~ % 

IMPORTINT TASK

mport copy
import json
import os
from pathlib import Path
import sys
import warnings
import torch
from anndata import AnnData
import scanpy as sc
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import pandas as pd
import tqdm
import gseapy as gp

from torchtext.vocab import Vocab
from torchtext._torchtext import (
    Vocab as VocabPybind,
)

sys.path.insert(0, "../")
import scgpt as scg
from scgpt.tasks import GeneEmbedding
from scgpt.tokenizer.gene_tokenizer import GeneVocab
from scgpt.model import TransformerModel
from scgpt.preprocess import Preprocessor
from scgpt.utils import set_seed 

os.environ["KMP_WARNINGS"] = "off"
warnings.filterwarnings('ignore')

IMPORT ERROR 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[29], line 24
     19 from torchtext._torchtext import (
     20     Vocab as VocabPybind,
     21 )
     23 sys.path.insert(0, "../")
---> 24 import scgpt as scg
     25 from scgpt.tasks import GeneEmbedding
     26 from scgpt.tokenizer.gene_tokenizer import GeneVocab

File ~/Documents/PR/scGPT/tutorials/../scgpt/__init__.py:18
     15     handler.setFormatter(formatter)
     16     logger.addHandler(handler)
---> 18 from . import model, tokenizer, scbank, utils, tasks
     19 from .data_collator import DataCollator
     20 from .data_sampler import SubsetsBatchSampler

File ~/Documents/PR/scGPT/tutorials/../scgpt/scbank/__init__.py:17
     14 handler.setFormatter(formatter)
     15 logger.addHandler(handler)
---> 17 from .databank import DataBank
     18 from .data import *
     19 from .setting import Setting

File ~/Documents/PR/scGPT/tutorials/../scgpt/scbank/databank.py:11
      9 from anndata import AnnData
     10 from datasets import Dataset, load_dataset
---> 11 from scvi import settings
     13 from scgpt.tokenizer import GeneVocab
     14 from .data import DataTable, MetaInfo

ImportError: cannot import name 'settings' from 'scvi' (/Applications/anaconda3/envs/scGPT_new/lib/python3.9/site-packages/scvi/__init__.py)

**Comment by subercui** [comment]
This looks like an issue with `scvi` installation. Can you try in a python console of the same env:
```python
import scvi
from scvi import settings
```

and which version of `scvi-tools` you are using?

**Comment by AshirBorah** [comment]
I had this too by the error was solved by installing the latest version of scvi. The latest version of Pydantic has some breaking changes too. A requirements files or a conda environment file would be very helpful

**Comment by subercui** [comment]
Hi, we have recently optimized the imports and updated a new version.

Now the scvi would only be used in tutorials for getting some datasets they hosted. The recommended version for it is around 0.16.0 

Thanks and please let me know if any feedback
