### ISSUE TITLE
No module names 'scgpt.tasks' 

### ISSUE THREAD

**Issue by Louis-mishka** [bowang-lab/scGPT#31]
Congratulations on your work, the paper and your models seem super exciting! Hopefully this is just the beginning of LLM style training and insights for omics data. 

I have been trying to get the scgpt package working for a couple of days now. I ran into a number of issues with installation that have been discussed by others here. I now have one remaining error while trying to run the GRN tutorial. 

import copy
import json
import os
from pathlib import Path
import sys
import warnings

import torch
from anndata import AnnData
import scanpy as sc
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import pandas as pd
import tqdm
import gseapy as gp

from torchtext.vocab import Vocab
from torchtext._torchtext import (
    Vocab as VocabPybind,
)

sys.path.insert(0, "../")
import scgpt as scg
from scgpt.tasks import GeneEmbedding
from scgpt.tokenizer.gene_tokenizer import GeneVocab
from scgpt.model import TransformerModel
from scgpt.preprocess import Preprocessor
from scgpt.utils import set_seed

OUT 

os.environ["KMP_WARNINGS"] = "off"
warnings.filterwarnings('ignore')

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[39], line 26
     24 sys.path.insert(0, "../")
     25 import scgpt as scg
---> 26 from scgpt.tasks import GeneEmbedding
     27 from scgpt.tokenizer.gene_tokenizer import GeneVocab
     28 from scgpt.model import TransformerModel

ModuleNotFoundError: No module named 'scgpt.tasks'

apologies if this is a simple solve I am not sure what else to try. 

In case anyone else is interested in the installation issues I will include the order of installations which I used to successfully import at least the other parts of the package. 

#Make sure you have CUDA 11.7 installed download here windows - https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local
#Make sure you have Visual Studio installed with microsoft C++ build tools. https://visualstudio.microsoft.com/visual-cpp-build-tools/
#Make sure you have R 4.1.1 installed
#Open anaconda 
#conda create -n sctgpt python=3.9
#conda activate sctgpt 
#conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.7 -c pytorch -c nvidia
#conda install -c anaconda git
#pip install git+https://github.com/HazyResearch/flash-attention.git@v1.0.4
#conda install -c conda-forge rpy2
#pip install scgpt
#pip install jupyter
#pip install gseapy

**Comment by hamzanasirr** [comment]
We are facing the same issue.

**Comment by Louis-mishka** [comment]
I looked in the scgpt files, there is file named tasks which contains python file (from memory) _int. Copy and pasted this into Jupiter notebook. Ran before scgpt import and all worked fine.

Sent from my iPhone

On 10. Jul 2023, at 17.41, Hamza Nasir ***@***.***> wrote:

﻿

We are facing the same issue.

**Comment by subercui** [comment]
Hi, thanks for raising the issue. It seems there was a mistake when merging the code into main. Let me fix it right now

**Comment by subercui** [comment]
Please let me know if there is any further question about this
