### ISSUE TITLE
Perturbation Example - request

### ISSUE THREAD

**Issue by simon-harvEDU** [bowang-lab/scGPT#33]
Hi Team,
amazing work! 
Do you have an example notebook for a perturbation analysis by any chance?
Would help us to get new insights and accelerate our work a lot : ) 

The perturbation data passed on to the model could be also a crispr-perturbation of a image based read out?

Thanks,
Simon

**Comment by subercui** [comment]
Hi, we have provided a notebook in the tutorials folder and will also upload it to the documentation site soon. The notebook works on the Adamson dataset, which is sequencing based. I hope it can help your application
