### ISSUE TITLE
Error during training in Fine-tuning on Pre-trained Model for Cell-type Annotation

### ISSUE THREAD

**Issue by Ragagnin** [bowang-lab/scGPT#35]
Hello, congratulations on the project.
I'm trying to run the Fine-tuning on Pre-trained Model for Cell-type Annotation using the provided database and checkpoint. However, I keep getting this error:

**TypeError Traceback (most recent call last)
<ipython-input-33-e8665e5eff17> in <cell line: 6>()
23
24 if config.do_train:
---> 25 train(
26 model,
27 loader=train_loader,

7 frames
/content/scGPT/scgpt/model/model.py in forward(self, src, src_mask, src_key_padding_mask, **kwargs)
684 else:
685 # NOTE: the FlashMHA uses mask 0 for padding tokens, which is the opposite
--> 686 src_key_padding_mask_ = ~src_key_padding_mask
687
688

TypeError: ~ (operator.invert) is only implemented on integer and Boolean-type tensors**

I have tried to fix this error in numerous ways, but without success.
Has anyone else experienced this issue? I have tried modifying the train() function and the model.py file, but without success. Am I missing an important part of the fine-tuning process?
Thank you in advance.

**Comment by Ragagnin** [comment]
Hello, thank you for responding!
I am using this version of PyTorch
2.0.1+cu117

**Comment by subercui** [comment]
I think that explains it. I made a temporary fix here, which will simply convert the data type. I hope to find a better and safer solution and let me know if you have any suggestions.

https://github.com/bowang-lab/scGPT/blob/40d69ac9cd6ae079b7af96ffdadef3669832d9fb/scgpt/model/model.py#L685-L688

Let me know if this works for you.

**Comment by Ragagnin** [comment]
It worked very well! Thank you!
