### ISSUE TITLE
About the input cell type condition

### ISSUE THREAD

**Issue by AllenShow** [bowang-lab/scGPT#38]
Hi, thank you for the great work.
In the pretraining procedure, concerning generating whole genome expression given an input cell type condition, i.e., generation by “cell prompts”, where is the cell type condition from? Does it mean that the cell type information of the pretraining dataset is used for pretraining? So it is a supervised pretraining procedure? If I misunderstood, forgive me please.

**Comment by subercui** [comment]
Hi Allen, thank you for the question. (1) The pre-training is self-supervised. "Cell prompt" uses the embedding of the same cell. To be specific, the model takes in the expression of genes and generates the cell embedding. This embedding will be used as a cell prompt in the generation training. (2) In the inference stage, annotated type conditions can be used. If you want to generate a typical cell for cell type A, you may use the average cell embedding of type A as a "cell prompt". We also plan to make an example to show this application to make this scenario more clear. Please stay tuned

**Comment by rafaella-buzatu** [comment]
> Hi Allen, thank you for the question. (1) The pre-training is self-supervised. "Cell prompt" uses the embedding of the same cell. To be specific, the model takes in the expression of genes and generates the cell embedding. This embedding will be used as a cell prompt in the generation training. (2) In the inference stage, annotated type conditions can be used. If you want to generate a typical cell for cell type A, you may use the average cell embedding of type A as a "cell prompt". We also plan to make an example to show this application to make this scenario more clear. Please stay tuned

Is there already a tutorial available for how to use the model for generation from "cell prompts" and "gene prompts"?
