### ISSUE TITLE
TypeError: bwd(): incompatible function arguments

### ISSUE THREAD

**Issue by yzhu-bnt** [bowang-lab/scGPT#43]
File [~/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py:44](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a22626e742d67622d797a68752d67355f7363475054227d.vscode-resource.vscode-cdn.net/home/ubuntu/scGPT/~/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py:44), in _flash_attn_backward(dout, q, k, v, out, softmax_lse, dq, dk, dv, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, dropout_p, softmax_scale, causal, rng_state, num_splits, generator)
     36 """
     37 num_splits: whether to parallelize over the seqlen_k dimension (num_splits > 1) or
     38 not (num_splits = 1). num_splits=0 means it will be set by an internal heuristic.
   (...)
     41 This hyperparameter can be tuned for performance, but default value (heuristic) should work fine.
     42 """
     43 dout = dout.contiguous()  # CUDA code assumes that dout is contiguous
---> 44 _, _, _, softmax_d = flash_attn_cuda.bwd(
     45     dout, q, k, v, out, softmax_lse, dq, dk, dv, cu_seqlens_q, cu_seqlens_k,
     46     max_seqlen_q, max_seqlen_k, dropout_p, softmax_scale, False, causal,
     47     # num_splits, generator, rng_state)
     48     num_splits, generator)
     49 # if dk.isnan().any() or dk.isnan().any() or dv.isnan().any() or softmax_d.isnan().any():
     50 #     breakpoint()
     51 return dq, dk, dv, softmax_d

TypeError: bwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor, arg6: at::Tensor, arg7: at::Tensor, arg8: at::Tensor, arg9: at::Tensor, arg10: at::Tensor, arg11: int, arg12: int, arg13: float, arg14: float, arg15: bool, arg16: bool, arg17: int, arg18: Optional[at::Generator], arg19: Optional[at::Tensor]) -> List[at::Tensor]

Invoked with: tensor([[[-28.0938,  52.8125, -32.2812,  ...,  34.6250,  57.3125,  41.6562],

**Comment by yzhu-bnt** [comment]
flash-attn 1.0.3. 
CUDA Version: 12.0   
python 3.8
torch 1.13.0

**Comment by subercui** [comment]
HI, the error message indicates a data type issue. Are you running any of the tutorial notebook or example code? If you use your own script, do you mind sharing more information?

**Comment by yzhu-bnt** [comment]
I am running the tutorial 'Tutorial_Annotation.ipynb' using the sample data. 
[scGPT](https://github.com/bowang-lab/scGPT/tree/main)/[tutorials](https://github.com/bowang-lab/scGPT/tree/main/tutorials)
/Tutorial_Annotation.ipynb

I was using your 'scGPT_human' pertained model and using the 'c_data.h5ad' data you provided. All codes worked well until Step 4: Finetune scGPT with task-specific objectives.

**Comment by yzhu-bnt** [comment]
'a data type issue' gave me confident to just repeat the run again. 
I am still not sure where made a difference, but this time the tutorial has worked through! 
Thank you for your timely response!

**Comment by subercui** [comment]
Yeah, I think it is related to some env setting, but seems difficult to reproduce. Glad to know it works now! Going to close the issue for now
