### ISSUE TITLE
Pre-training cost

### ISSUE THREAD

**Issue by czifan** [bowang-lab/scGPT#5]
Thanks for sharing your code!
I have a question about pre-training. How long does pre-training take, on what GPU, and how many GPUs?

**Comment by bSwain-git** [comment]
I'd also like to know the answer to this - is it something an individual can run?

**Comment by subercui** [comment]
Hi, currently, we use four A100 GPUs to pretrain the model on 10.3 million cells. It takes about 3 days for the training of 6 epochs.

**Comment by bSwain-git** [comment]
Thanks a lot for the quick reply! Was training finished after those 6 epochs?

**Comment by subercui** [comment]
Yes, we train for 6 epochs by default for now.

**Comment by bSwain-git** [comment]
Fantastic, thanks for the fast responses.
