### ISSUE TITLE
ValueError: Length of values (259) does not match length of index (755)

### ISSUE THREAD

**Issue by yueming-ding** [bowang-lab/scGPT#50]
Nice work! I will be very helpful for single cell research! We are testing to annotate the cell type for our internal single cell data with your scGPT. But when we ran the step 5: Inference with fine-tuned scGPT model, we got the following error:
ValueError: Length of values (259) does not match length of index (755)

Our train subset has 2007 cells and test subset has 259 cells. Could you help what the above error means? Thanks

**Comment by subercui** [comment]
Hi @yueming-ding , can you provide the full trace stack, so I can know where this error occurs? Just a glimpse, this might be some input dimension mismatch. Some of your input data to the model may has a length of 259, but others have 755.

**Comment by yueming-ding** [comment]
Hi subercui, thanks for your quick response! I'm attaching the following 2 screenshots. Please let me know if you need more info.
<img width="1322" alt="Screenshot 2023-07-28 at 6 18 02 PM" src="https://github.com/bowang-lab/scGPT/assets/1060297/96c18c2a-6365-4ea6-8914-bdac8e1eb57e">
<img width="1030" alt="Screenshot 2023-07-28 at 6 18 18 PM" src="https://github.com/bowang-lab/scGPT/assets/1060297/bdcafac7-c9f0-4542-88d4-c13be322892a">

**Comment by yueming-ding** [comment]
Hi @subercui, our adata has 7549 × 31923 and  adata_test has 755 × 31923. But after running the step "preprocessor = Preprocessor()", adata reduced to 2007 × 22129 and adata_test to 259 × 22129. Some cells were somehow filtered out. We used the same parameters as your tutorials for preprocessor:
preprocessor = Preprocessor(
    use_key="X",  # the key in adata.layers to use as raw data
    filter_gene_by_counts=filter_gene_by_counts,  # step 1
    filter_cell_by_counts=False,  # step 2
    normalize_total=1e4,  # 3. whether to normalize the raw data and to what sum
    result_normed_key="X_normed",  # the key in adata.layers to store the normalized data
    log1p=data_is_raw,  # 4. whether to log1p the normalized data
    result_log1p_key="X_log1p",
    subset_hvg=False,  # 5. whether to subset the raw data to highly variable genes
    hvg_flavor="seurat_v3" if data_is_raw else "cell_ranger",
    binning=n_bins,  # 6. whether to bin the raw data and to what number of bins
    result_binned_key="X_binned",  # the key in adata.layers to store the binned data
)

**Comment by subercui** [comment]
Hi @yueming-ding , thank you for sharing the info. In the screenshot, I can't see which line raised the error. Is it the umap plot? Can you provide the full trace and it seems a mismatch in a pandas dataframe

**Comment by subercui** [comment]
The preprocessor itself should not filter cells. Can you check between notebook cells and see at which step the cells got removes?

Right now, I would guess it is probably here

![image](https://github.com/bowang-lab/scGPT/assets/11674033/f9e3c9bb-3a8a-4ca6-ac92-005985979cc2)

Maybe in your custom dataset, you set the "str_batch" differently?

**Comment by subercui** [comment]
By the way, I would suggest you subset the genes to a few thousand highly variable genes. It would make the computing faster and probably more accurate as well

**Comment by yueming-ding** [comment]
> The preprocessor itself should not filter cells as long as `filter_cell_by_counts=False`. Can you check between notebook cells and see at which step the cells got removed?
> 
> Right now, I would guess it is probably here
> 
> ![image](https://user-images.githubusercontent.com/11674033/260544598-f9e3c9bb-3a8a-4ca6-ac92-005985979cc2.png)
> 
> Maybe in your custom dataset, you set the "str_batch" differently?

@subercui Thanks for your response! We found that cells were filtered out at "Filter cells by counts" step although we set "filter_cell_by_counts=False". We also found that cells were filtered at "Filter cells by counts" step for some datasets and were not filtered for some other dataset although we use the same "filter_cell_by_counts=False". It is very strange.

**Comment by yueming-ding** [comment]
> By the way, I would suggest you subset the genes to a few thousand highly variable genes. It would make the computing faster and probably more accurate as well

Do you mean to set the following variable to a few thousand highly variable genes? e.g. subset_hvg=4000? I saw it was set as False in your tutorial: "subset_hvg=False,  # 5. whether to subset the raw data to highly variable genes". But even you set "subset_hvg=False", both train and valid set have only 3001 gene left after running tokenized_train and tokenized_valid: scGPT - INFO - train set number of samples: 7059,
         feature length: 3001
scGPT - INFO - valid set number of samples: 785,
         feature length: 3001

**Comment by yueming-ding** [comment]
> By the way, I would suggest you subset the genes to a few thousand highly variable genes. It would make the computing faster and probably more accurate as well

@subercui Do you mean to set the following variable to a few thousand highly variable genes? e.g. subset_hvg=4000? I saw it was set as False in your tutorial: "subset_hvg=False, # 5. whether to subset the raw data to highly variable genes". But even you set "subset_hvg=False", both train and valid set have only 3001 gene left after running tokenized_train and tokenized_valid: scGPT - INFO - train set number of samples: 7059,
feature length: 3001
scGPT - INFO - valid set number of samples: 785,
feature length: 3001
Thanks!

**Comment by subercui** [comment]
The feature length or `max_seq_len` in the notebook is a different concept. It controls how long the input to the model can be. If your input number of genes is longer than the `max_seq_len`, it will subsample the genes to the max number.

![image](https://github.com/bowang-lab/scGPT/assets/11674033/ffaf5490-59ce-4c9b-9714-51424df3db52)

HVGs work differently and it is a step in preprocessing the data, and yes, you can well set it by `subset_hvg` in the preprocessor. One typical use case is that you can set the `subset_hvg=max_seq_len-1`, where the additional 1 dimension is for cls token which will be appended to the input in the tokenization step.

Admittedly, the notebook contains quite some code lines during development. We will try to clean it and make it more clearly self-explaining. Will update it soon

**Comment by subercui** [comment]
Hi, going to close the issue for now. Please let me know if you have further questions

**Comment by yueming-ding** [comment]
> Hi, going to close the issue for now. Please let me know if you have further questions

@subercui Thanks! We are testing subset_hvg as you recommended. I'll update you when we have results.
