### ISSUE TITLE
pert_flags in perturbation prediction

### ISSUE THREAD

**Issue by WenzhuoTang** [bowang-lab/scGPT#52]
Hi,

Thanks for sharing the tutorials of downstream tasks! Your work is inspiring! 

While I was trying to reproduce the perturbation prediction task, I noticed that the pipeline subtracts `pert_flags` from the batch produced by `gears.PertData` with shape \(batch_size $\times$ n_genes\). The original dataloader of GEARS does not produce any perturbation-related feature that has the same shape as input data. Could you explain how we can generate the `pert_flags` from data?

**Comment by yanwu2014** [comment]
I'm running into the same issue, were you able to figure out what `pert_flags` is supposed to be?

**Comment by yanwu2014** [comment]
Ah also found the solution here: https://github.com/bowang-lab/scGPT/issues/36
