### ISSUE TITLE
On the use targeted scRNA-seq datasets

### ISSUE THREAD

**Issue by krejciadam** [bowang-lab/scGPT#54]
Hi!
Thank you for this work and the support here on github! 

I have more of a conceptual question, partially in line with #36 

There is a type of data never mentioned around here - targeted single-cell transcriptomics. In these datasets, one uses multiplex PCR (or alternatively, oligo probes) to capture transcripts originating from a panel of, say, few hundred genes. So in each cell, most genes are always zero, except for the panel genes, which are, on the other hand, captured with great sensitivity. Due to this hugely superior sensitivity, these datsets typically don't really look just like a subset of standard WTA datasets where out-of-panel genes are set to zero. 

Moreover, targeted datasets with perturbations exist (see e.g. here: https://pubmed.ncbi.nlm.nih.gov/32483332/). In these datasets, many perturbed genes will not be part of the targeted panel. It can go as extreme as this dataset (https://aacrjournals.org/cancerres/article/83/8_Supplement/LB249/725533/Abstract-LB249-A-genome-scale-CROP-seq-screen), where 18 500 genes are perturbed, but only 374 genes sequenced as part of the targeted panel. 

How would you go about such datasets? My current thinking is that it should be possible to work with them without big modifications and they could still benefit from the pre-trained foundation model, but I'd like to hear your thoughts on it. Thank you!

**Comment by subercui** [comment]
Hi @krejciadam , thank you so much! I haven't tried any of the targeted Perturb-seq , but it looks super interesting given what you have said. I'll have an in-depth read into the references you shared. 

I think the challenge will be how to process the perturbed genes and the readout target genes together. For example, if you are interested in a perturbation response prediction for the 374 target genes:
1. For each example in a training mini-batch, the input tokens could contain 1 + 374 genes. Here 1 means the perturbed gene x in a corresponding condition out of the 18500.

2. The pretraining model weights could be loaded. Hopefully, they may help as well

Let me know if this could fit your need, and I am more than happy to discuss this further
