### ISSUE TITLE
Issue about highly variable genes

### ISSUE THREAD

**Issue by SuperChanS** [bowang-lab/scGPT#6]
I notice that in the the function of Preprocessor, the number of genes is limited to the n_hvg. 

However, I think the scanpy calculation cannot represent biological significance. Thus, I want to learn more about the selection of this parameter and what you think of it.

Besides, if the downstream task such as cell type annotation, perturbation prediction and cell generation are also finished using the highly variable genes.

**Comment by subercui** [comment]
Hi, I am sure I fully understand your question. If your question is about the efficacy of the scanpy hvg computation, I think it has been widely used in single-cell community. If you have a specific alternative, I am willing to have a try. 

In the meantime, the script we provided serves as an example, and I believe scGPT would support alternative preprocessing configs as well, such as alternative numbers or selection of hvgs. Just keep in mind, a higher number of hvgs would consume more GPU memories, so you might want to balance with other configs such as the batch size.

We also plan to release memory-efficient fine-tuning in the future, please stay tuned.
