### ISSUE TITLE
Dataset download instruction

### ISSUE THREAD

**Issue by yuzhenmao** [bowang-lab/scGPT#60]
Hi,

Thanks for the amazing work! I have read the section4.6 about the dataset. Also, I noticed in the current repo, there is a directory ([data/cellxgene](https://github.com/bowang-lab/scGPT/tree/main/data/cellxgene)) which seems to be related to the dataset download, but it is still a little unclear to me. 

Could you please provide the code that downloads the data from the original webset? The ideal case is that after running the code, I could directly run the training code afterwards. I think that would be very helpful.

Thank you very much!

**Comment by subercui** [comment]
Hi, thank you for the question. Currently, there is a readme in the folder. Upon your request, we are trying to update it to make it more clear. Was originally planning to reply once it updated 😄  but I just saw you closed the issue. Just want to make sure if you have found the solution you need?

**Comment by yuzhenmao** [comment]
Thanks, that sounds good to me!

**Comment by subercui** [comment]
Hi @yuzhenmao , please see the newly updated readme and scripts in the data/cellxgene folder
