### ISSUE TITLE
Downsampling Strategy

### ISSUE THREAD

**Issue by yuzhenmao** [bowang-lab/scGPT#61]
Hi,

Thank you for the amazing work! May I ask what is the sampling strategy used in the paper when depicting Figure 2 E&F, where only 300K cells are used to pre-train the model.

Thanks!

**Comment by subercui** [comment]
Hi, thanks for the question. We simply did a ransom subsampling for that experiment. For example, each cell from the whole 33M collection will have the same around 1/100 probability to be selected, and then this makes the 300K training examples.

**Comment by yuzhenmao** [comment]
Thanks for the reply! That makes sense to me.
