### ISSUE TITLE
Question abouts comparing between cell states (healthy v.s. diseased) using Attention-based GRN Inference

### ISSUE THREAD

**Issue by ZhuoliHuang** [bowang-lab/scGPT#65]
Hi, scGPT is awesome, Many thanks for your work.

I am trying to compare between cell states (healthy v.s. diseased), to find the genes which are most influenced by disease. I have followed the "Tutorial_Attention_GRN" and successfully got "dict_sum_condition_mean" with gene * gene attention matrix for healthy ceclls and diseased cells. However, there are a few things that confuse me:

(1) In gene * gene attention matrix, row names and column names are same genes, but the values are not symmetric, so what is the different biological meaning of row names or column names? (I guess row names are targets?)

(2) Using "setting == 'difference", the Tutorial selecting the top 20 value in 'exp-control', which only select positive value. What is the biological meaning of negative value produced by 'exp-control' (green color in heatmap like figure6B), are negative value also important? 

(3) Could you please give me some advice about how to get genes which are most influenced by disease using "dict_sum_condition_mean" ? I can not follow the Tutorial because I do not have prior known perturbed gene in my data.

**Comment by subercui** [comment]
Hi, thank you! Regarding your questions:

(1) The matrix contains the attention scores between genes. We usually call row-wise tokens the queries. Technically, the model is optimized to learn the query representations by integrating the token representations across columns. You may have a look at this wonderful blog as well http://jalammar.github.io/illustrated-transformer/. Intuitively, the attention score tells how much the influencer gene (column-wise) contributes to the representation of a query gene (row-wise). This also explains why it is asymmetric. So, in a GRN setting where you pick a transcriptional factor as an "influencer gene", then the rows with the highest scores tell the genes that are most influenced by the influencer. This is what we are trying to show in Figure 6.

(2) Therefore, in the "difference" setting, a positive value tells there is an increasing influence to this gene, and that is exactly what we want to find in the experiment, in other words, the group of genes "differentially" highly influenced by a perturbed gene. Similarly, I would say the negative values indicate a relatively lower influence between the "before" condition and the "after" condition. Depending on the specific research question you work on, that information could be interesting as well.

(3) That is indeed an interesting question! The workflow was originally demonstrated for perturbation data, where the selection of the "influencer" genes is rather clear. We are currently also trying to test for disease datasets. I would suggest you may start with selecting some marker genes or well-established influencer genes for the specific condition you are working with. 

I hope these may provide a better explanation.

@ChloeXWang If you have better explanations or advice, please feel free to comment as well 😄 , especially on point 3

**Comment by ZhuoliHuang** [comment]
@subercui Thanks for such a detailed and authentic response, exactly what I needed.
