### ISSUE TITLE
Order of normalization of log1p for data preprocessing

### ISSUE THREAD

**Issue by KatarinaYuan** [bowang-lab/scGPT#66]
Hi, I feel confused about the order that we should adopt foe normalization and log1p. In cell type classification, log1p is conducted before normalization, while from tutorials, they would do normalization first and the log1p. Could you please provide more detailed explanation about this part? Thank you

**Comment by subercui** [comment]
Hi, thanks for the question. I think we maintained the consistency in most of the cases. Could you let us know the specific lines of code you point to?

For example, we used the same `Preprocessor ` to conduct the preprocessing. In the [Annotation Tutorial](https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Annotation.ipynb):

![image](https://github.com/bowang-lab/scGPT/assets/11674033/9146b24c-9c0a-4660-8a23-be80929033f3)

In the [Integration Tutorial](https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Integration.ipynb):

![image](https://github.com/bowang-lab/scGPT/assets/11674033/1d9a4188-8e89-4cbf-8838-092b51e34de9)

So by default, the preprocessor would normalize first and then do log1p transformation. If you refer to the point that the preprocessor in annotation skipped the log1p as shown in the first screenshot, this is a data-specific setting. The data we used here has already been log-transformed, so we tell the preprocessor to skip the step by the `data_is_raw` flag.

BTW, for these applications, we applied the binning strategy. Therefore, the log and normalization would only influence the selection of highly variable genes. In other words, if given the same set of highly variable genes, the binning step would provide the same final data values regardless of what order of normalization or log1p.

**Comment by subercui** [comment]
Going to close the issue for now. Let me know if you have further questions
