### ISSUE TITLE
Comparison with scBERT?

### ISSUE THREAD

**Issue by HelloWorldLTY** [bowang-lab/scGPT#7]
Hi, thanks for your great work! But I have used a similar tool published here: https://www.nature.com/articles/s42256-022-00534-z.

which is also based on large lanugage model. I am not satisified with the performance of scBERT, so do you consider adding it as a baseline model? Thanks.

**Comment by subercui** [comment]
Hi, thanks for the suggestion. As you mentioned, I think scBERT was mainly designed for cell type annotation. We indeed have considered benchmarking with it, and scGPT performs better based on some preliminary results we tested. We are currently working on more benchmarking and other extensions as well. The results will be added to a newer version of our manuscript.

Here is a preliminary comparison I have, in a cell type annotation setting:
<img width="600" alt="image" src="https://github.com/bowang-lab/scGPT/assets/11674033/cdbe4df3-57bf-4202-9aa6-1ab5ddc33dae">

Please note, the comparison and results may change later in our formal release.

In the meantime, feel free to apply scGPT in your workflow. We'll provide clean example scripts for various fine-tuning tasks soon as well. Please see the plan [here](https://github.com/bowang-lab/scGPT#to-do-list)
