### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by HJamieJ** [bowang-lab/scGPT#70]
Hi, it seems the python version I am using is not suitable for scGPT

ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.7.1,<3.11; 0.1.1 Requires-Python >=3.7.1,<3.11; 0.1.2 Requires-Python >=3.7.13,<3.11; 0.1.2.post1 Requires-Python >=3.7.13,<3.11
ERROR: Could not find a version that satisfies the requirement scgpt (from versions: none)
ERROR: No matching distribution found for scgpt

Are you planning on making updates for the latest version of Python soon?

**Comment by subercui** [comment]
Hi, thanks for the question. Which version of you are using?

**Comment by HJamieJ** [comment]
Hi, thank you for your response.

It is 3.11.4, the latest version of Python, I believe

**Comment by subercui** [comment]
I created a new release `v0.1.3` and relaxed the Python version requirement. You may install it via pypi now. Please note that the package has not actually been tested in 3.11. Let me know if you have further questions

**Comment by subercui** [comment]
Could you install it with python 3.11 now?

**Comment by HJamieJ** [comment]
Hi,
 
 Apologies for the delayed response. I do not think it worked? I see that there was an error:
 
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by subercui** [comment]
Hi @HJamieJ, can you share more context of the error message, for example, a few lines above should have indicated which package encountered the error.

In the meantime, I leaning toward rewinding back the python version limitations. It does seem some dependencies like numba or flash-attn may not work very well with the newest python like 3.11.

So, I would also strongly recommend you use `python >=3.7.13 <=3.10`. You can usually create a virtual env easily with conda, such as `conda create -n env_name python=3.7.13`, and work within the created virtual environment. Let me know if you need any help

**Comment by HJamieJ** [comment]
Hi, apologies for the delay.
Here is the full error:

py -m pip install scgpt "flash-attn<1.0.5"

Collecting scgpt
  Obtaining dependency information for scgpt from https://files.pythonhosted.org/packages/46/7f/a95491c8f4dcafbef22ff6c0003f59fb6816729b9a19ed339ca4dd13a117/scgpt-0.1.5-py3-none-any.whl.metadata
  Downloading scgpt-0.1.5-py3-none-any.whl.metadata (7.9 kB)
Collecting flash-attn<1.0.5
  Downloading flash_attn-1.0.4.tar.gz (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 32.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Jim_Jee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Jim_Jee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Jim_Jee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Jim_Jee\AppData\Local\Temp\pip-build-env-ds5xv71m\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Jim_Jee\AppData\Local\Temp\pip-build-env-ds5xv71m\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\Jim_Jee\AppData\Local\Temp\pip-build-env-ds5xv71m\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Jim_Jee\AppData\Local\Temp\pip-build-env-ds5xv71m\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
