### ISSUE TITLE
Error during install in HPC

### ISSUE THREAD

**Issue by blackwidowst** [bowang-lab/scGPT#74]
I am getting an error when trying to install, please help:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fsgv573f/flash-attn_f375291c450540ad8ce1e11cb0a1eef7/setup.py", line 8, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

<img width="555" alt="scgpt" src="https://github.com/bowang-lab/scGPT/assets/143217079/03bf0291-3322-43ff-b080-4b4f7af8ae6a">

**Comment by subercui** [comment]
Hi, flash-attn 1.0.9 may be too new a version. Can you try `pip install "flash-attn<1.0.5"`. Meanwhile, you may have a look at this one https://github.com/Dao-AILab/flash-attention/issues/453#issuecomment-1692678358 . It seems related

**Comment by blackwidowst** [comment]
Thank you.  I tried this but unfortunately now I have a new error related to CUDA.  We do have our cuda programs /usr/local/cuda so I am not sure what exactly it is looking for:

Collecting flash-attn<1.0.5
  Using cached flash_attn-1.0.4.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-susw7sc4/flash-attn_470685584d364aeea1ef393a2775577f/setup.py", line 81, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "/tmp/pip-install-susw7sc4/flash-attn_470685584d364aeea1ef393a2775577f/setup.py", line 24, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
        File "/usr/local/anaconda3-2020/envs/scgpt/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/local/anaconda3-2020/envs/scgpt/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/local/anaconda3-2020/envs/scgpt/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/local/anaconda3-2020/envs/scgpt/lib/python3.8/subprocess.py", line 1720, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'

      Warning: Torch did not find available GPUs on this system.
       If your intention is to cross-compile, this is not an error.
      By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
      Volta (compute capability 7.0), Turing (compute capability 7.5),
      and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
      If you wish to cross-compile for a single specific architecture,
      export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

      [end of output]

**Comment by Bec-k** [comment]
same here

**Comment by subercui** [comment]
Hi @blackwidowst, did you solve it?

**Comment by blackwidowst** [comment]
It is not working yet, still trying.

**Comment by Allamyh** [comment]
I got the same error message, solved by installing the "packaging" module. In my case "$ pip install packaging"

**Comment by blackwidowst** [comment]
I was finally able to get it running but now having an issue with the program.  When running the sample code available at https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Reference_Mapping.ipynb, the function scg.tasks.embed_data() in the code throws an error saying: AttributeError: module 'scgpt.tasks' has no attribute 'embed_data' 

Has anyone run into this?

**Comment by subercui** [comment]
Hi, @blackwidowst 

1. If you run the code in the main branch, meaning if you have cloned and updated the repo and run the notebook in the tutorials folder, then the function should be accessible. Here in the the tutorial,
![image](https://github.com/bowang-lab/scGPT/assets/11674033/8c58398b-ae62-4ea8-94f4-7c8101983c76)
It tries to import the code in the cloned repo and the function is imported here https://github.com/bowang-lab/scGPT/blob/ba9b9efeedeeaf64618e50f62218309d07b2f179/scgpt/tasks/__init__.py#L2

3. If you try to run the code with the pip installed package, meaning if you just pip installed the package without downloading the repo. Then please update to the newest version by `pip install -U scgpt`. I just released the new version 0.1.5, and it has this new feature now.

Please let me know how it works
