### ISSUE TITLE
Questions for Perturbation Training

### ISSUE THREAD

**Issue by taffy-miao** [bowang-lab/scGPT#79]
Hi Team, I'm using the GEARS package to train scGPT from local dataset. However, my dataset contains more cells than the GEARS can managed, so is that possible for me to split my data into pieces, and train the model several times to reach the similar outcome that I train it with the complete dataset?

**Comment by taffy-miao** [comment]
And I'm facing a problem using GEARS to import my own data:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_1143058/1783411457.py in <module>
      1 pert_data = PertData("./data/")
----> 2 pert_data.new_data_process(dataset_name = 'xialab_perturb', adata = tmp_adata)

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in new_data_process(self, dataset_name, adata)
     94         dataset_fname = os.path.join(pyg_path, 'cell_graphs.pkl')
     95         print_sys("Creating pyg object for each cell in the data...")
---> 96         self.dataset_processed = self.create_dataset_file()
     97         print_sys("Saving new dataset pyg object at " + dataset_fname)
     98         pickle.dump(self.dataset_processed, open(dataset_fname, "wb"))

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in create_dataset_file(self)
    246         dl = {}
    247         for p in tqdm(self.adata.obs['condition'].unique()):
--> 248             cell_graph_dataset = self.create_cell_graph_dataset(self.adata, p, num_samples=1)
    249             dl[p] = cell_graph_dataset
    250         return dl

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in create_cell_graph_dataset(self, split_adata, pert_category, num_samples)
    283         if pert_category != 'ctrl':
    284             # Get the indices of applied perturbation
--> 285             pert_idx = self.get_pert_idx(pert_category, adata_)
    286 
    287             # Store list of genes that are most differentially expressed for testing

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in get_pert_idx(self, pert_category, adata_)
    252     def get_pert_idx(self, pert_category, adata_):
    253         pert_idx = [np.where(p == self.gene_names)[0][0]
--> 254                     for p in pert_category.split('+')
    255                     if p != 'ctrl']
    256         return pert_idx

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in <listcomp>(.0)
    253         pert_idx = [np.where(p == self.gene_names)[0][0]
    254                     for p in pert_category.split('+')
--> 255                     if p != 'ctrl']
    256         return pert_idx
    257 

IndexError: index 0 is out of bounds for axis 0 with size 0

I check the type of adata.X and the .obs .var needed, but it still came error

**Comment by subercui** [comment]
> Hi Team, I'm using the GEARS package to train scGPT from local dataset. However, my dataset contains more cells than the GEARS can managed, so is that possible for me to split my data into pieces, and train the model several times to reach the similar outcome that I train it with the complete dataset?

Do you mean a memory issue? In that sense, it is possible to split them into files and load them consecutively/randomly in minibatches during the training.

**Comment by subercui** [comment]
Which version of GEARs you are using? Currently we recommend version <=0.0.3. Please see the related issue #36

**Comment by nmahieu-empresstx** [comment]
Having tested 0.0.3 I think the tensor dimension issue is still present. 0.0.1 works for me but not 0.0.3.

**Comment by taffy-miao** [comment]
I've figured the problem, some of the genes that I perturbed is not contained in the .var dataframe. After I deleted those genes the model is working.
