### ISSUE TITLE
vocab file is missing

### ISSUE THREAD

**Issue by zduckwood** [bowang-lab/scGPT#80]
Hi, where to find the vocab which is required for processing data? 
https://github.com/bowang-lab/scGPT/blob/ba9b9efeedeeaf64618e50f62218309d07b2f179/data/cellxgene/array_build_scb.sh#L17

**Comment by subercui** [comment]
Hi, thank you for the question. If you are building your own data, it can be any json file that maps gene names in the data to integer ids. If you are working with cellxgene data similarly as indicated in the data/cellxgene folder, you may use the vocabulary we provided here, https://github.com/bowang-lab/scGPT/blob/main/scgpt/tokenizer/default_cellxgene_vocab.json

**Comment by subercui** [comment]
Thank you for bringing it up. These are some legacy namings. I've updated them in the new commit.

**Comment by subercui** [comment]
Hi, this sentence states the setting for the fine-tuning task, and yes, this is mainly for consideration of computational cost. For pretraining, there is no setting for highly variable genes. There is a setting for max input length, which happens to be 1200 as well. The pretraining code has not been fully merged, but you can find it in the `dev_temp` branch. If the number of non-zero expressed genes is larger than the max input length, genes would be randomly sampled to the length at each training iteration. So technically, all non-zero genes for a cell are included in the pretraining

**Comment by subercui** [comment]
Hi, you can find the setting in pretraining here https://github.com/bowang-lab/scGPT/blob/4068d67caaac1e28d56964da68e0214817e38428/examples/sbatch_census.sh#L39

Also, a soft reminder that I updated the link to the vocabulary file in the previous comment.

**Comment by subercui** [comment]
If I understand correctly, you are asking about the number of genes captured for each sequenced cell in the raw data. The pretraining data we used was collected from CellXGene, and the data contains samples from multiple studies. So, the capture rates can vary among them. We didn't compute the exact distribution for this. Simply based on our experience with the data, the number of non-zero genes is in the range of one thousand to several thousands for individual cells
