### ISSUE TITLE
myeloid data available?

### ISSUE THREAD

**Issue by rpeys** [bowang-lab/scGPT#81]
Hi! Thanks for a great repo and resource. I found google drive links in your tutorials for the M.S. and pancreas data used in your paper, and I was wondering if you plan to share something similar for the myeloid data? Would be really helpful for reproducing and building off your work! Thanks!

**Comment by subercui** [comment]
Hi, thank you for the suggestion! We have uploaded the links for the datasets. Please have a look at https://github.com/bowang-lab/scGPT/blob/main/data/README.md

**Comment by rpeys** [comment]
Thanks for the quick response, the new section in the readme is great!

**Comment by rpeys** [comment]
Thanks for the quick response, the new section in the readme is great!

**Comment by SELECT-FROM** [comment]
> Hi, thank you for the suggestion! We have uploaded the links for the datasets. Please have a look at https://github.com/bowang-lab/scGPT/blob/main/data/README.md

Hello, may I ask if the dataset provided for the cell type annotation task is the top 3000 HVG?
