### ISSUE TITLE
Seems like a bug in the open-source implementation of perturbtion prediction

### ISSUE THREAD

**Issue by HelloWorldLTY** [bowang-lab/scGPT#82]
Hi, thanks for your great work. When I tried to run the new perturbation prediction code, I found a bug:

![image](https://github.com/bowang-lab/scGPT/assets/43333475/b2df8940-94b2-4565-9356-0e4dc3d88884)

Could you please help me address it? Thanks.

**Comment by taffy-miao** [comment]
I've faced a similar error, and the solution is using the 0.0.1 version of cell-gears, I guess you may installed the 0.0.4 version?

**Comment by HelloWorldLTY** [comment]
@taffy-miao Hi, thanks for your feedback. But sorry I do not have plans to follow Taffy at Bilibili :). 

![image](https://github.com/bowang-lab/scGPT/assets/43333475/3757e0fe-f841-46d1-816a-ddd92ef654d0)

![image](https://github.com/bowang-lab/scGPT/assets/43333475/c0d3639c-3b03-4e0d-b723-e5c8d0cc751c)


I downgrade my gears to 0.0.1, but I still face this error. Is it possible to have a version with updated gears? Thanks.

**Comment by subercui** [comment]
Hi @HelloWorldLTY , after you reinstall gears 0.0.1, please also delete the downloaded data and let the package build it again. A similar discussion can be found at #36 as well. I've also added the dependency to the pyproject.toml and uploaded a new version. Hopefully, this will help avoid future confusion.

**Comment by HelloWorldLTY** [comment]
Thanks a lot for your explaniation!!!
