### ISSUE TITLE
a bug in preprocess.py

### ISSUE THREAD

**Issue by annezxu** [bowang-lab/scGPT#83]
Hi, I wanted to point out something I noticed that took me a long time to figure out.  

in preprocess.py  line 110, 
        # step 2: filter cells
        if isinstance(self.filter_cell_by_counts, int):

Even if self.filter_cell_by_counts is passed as False, the condition still yields true and the if block from 110-117 still runs 

I think this is a misunderstanding with the isinstance function, where the variable is initially defined as (line 23): filter_cell_by_counts: Union[int, bool] = False and is a bool type. However, because in python the bool class is a subclass of int, isinstance( a_bool_value , int ) will STILL return True regardless. 

However, this bug isn't fatal because in line 112 sc.pp.filter_cells (False) is the same as  filter cells >=0, just thought the code could be fixed to avoid future errors. Thanks!

**Comment by subercui** [comment]
Thank you for bringing it up! Honestly speaking, was not aware that bool inherits int before. I've fixed it in https://github.com/bowang-lab/scGPT/commit/c1d2101188b8c3d1c1269067f4c48fd3419b7192
