### ISSUE TITLE
Questions for Attention-GRN

### ISSUE THREAD

**Issue by taffy-miao** [bowang-lab/scGPT#89]
Hi team. I have a question regarding the use of scGPT. Suppose I have a substantial amount of perturbation data, for example, two thousand perturbed genes. After fine-tuning the model using these two thousand perturbed genes, I plan to use the fine-tuned model for generating the GRN. In this scenario, will the predictive capability of the model decrease?

My second question concerns the interpretation of positive and negative attention scores in the context of GRN network generation using perturbation data. How should I understand the positive and negative values in the final output attention scores?

for example:
![cluster](https://github.com/bowang-lab/scGPT/assets/76729973/b550d892-f09b-47ad-9eb7-f8205b6c7946)

Thank you.

**Comment by subercui** [comment]
Hi, just to confirm first, you have a dataset containing around 2000 perturbations and you finetuned on the data and try to use the GRN tutorial https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Attention_GRN.ipynb . Is it correct?

1. I think 2000 perturbations should be fine.

2. By default, the code in the tutorial use the "difference" setting, which compare the attention score in perturbed and in control. So a negative score means the attention score between the pair of genes decreases. I do recommend you try the "experiment" setting here too
![image](https://github.com/bowang-lab/scGPT/assets/11674033/cb8c5bff-65f8-46c5-b1c8-bc3ab16e0f8c)

    It shows the attention scores in the perturbed cells directly.
