### ISSUE TITLE
formula to calculate accuracy

### ISSUE THREAD

**Issue by yueming-ding** [bowang-lab/scGPT#91]
I saw the following formula to calculate accuracy in your scGPT paper:
Accuracy = tp / (tp + fp + tn + fn)

Should the numerator be: (tp + tn)? The correct formula should be:
Accuracy = (tp + tn) / (tp + fp + tn + fn)

**Comment by subercui** [comment]
Thank you so much! This indeed is a typo. The actual calculation should be correct since we used the sklearn interface. We will update this.
