### ISSUE TITLE
Where can I find the whole-body model?

### ISSUE THREAD

**Issue by alex-l-kong** [bowang-lab/scGPT#93]
I'm trying to go through the Tutorial_Annotation.ipynb notebook. However, I'm unable to find the link to download the pre-trained whole-body model. Can you please point me in the right direction?

**Comment by subercui** [comment]
Hi @alex-l-kong , here is the link for the model https://drive.google.com/drive/folders/1oWh_-ZRdhtoGQ2Fw24HP41FgLoomVo-y?usp=sharing . BTW, you can access all checkpoint folders [here](https://github.com/bowang-lab/scGPT#pretrained-scgpt-model-zoo)
