### ISSUE TITLE
Non-frozen pre-decoder weights

### ISSUE THREAD

**Issue by qxzzxq** [bowang-lab/scGPT#96]
Hi, it seems that the code for freezing the pre-decoder weights in the annotation tutorial (https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Annotation.ipynb) does not freeze any parameter:

```python3
# Freeze all pre-decoder weights
for name, para in model.named_parameters():
    print("-"*20)
    print(f"name: {name}")
    if config.freeze and "encoder" in name and "transformer_encoder" not in name:
    # if config.freeze and "encoder" in name:
        print(f"freezing weights for: {name}")
        para.requires_grad = False
```

Since `config.freeze` evaluates to `False` here.

The log shows the same number of parameters:
```
scGPT - INFO - Total Pre freeze Params 51341843
scGPT - INFO - Total Post freeze Params 51341843
```

Is it the intended behavior?

**Comment by subercui** [comment]
Hi, thank you for the question. Yes, this is the intended default behavior. We usually recommend full fine-tuning if sufficient computing resources. The freeze option can be used to greatly accelerate the training time and use much less memory. It can usually generate comparable results as well on user provided datasets.
