### ISSUE TITLE
relevant code about atac

### ISSUE THREAD

**Issue by hunxuewangzi** [bowang-lab/scGPT#98]
Hello, I would like to ask when you will release the relevant code about atac.
Thank you very much for your attention to this matter, and I look forward to your response. Your expertise and insights would be invaluable in helping me gain a deeper understanding of your research.

**Comment by subercui** [comment]
Hi, thank you for the question! Please see the recently uploaded multi-omics tutorial at https://github.com/bowang-lab/scGPT/blob/main/tutorials/Tutorial_Multiomics.ipynb . While the tutorial works on a CITE-seq data, running for atac-seq data would work similarly.

Please note that we are trying to simplify the code in that tutorial, you may have a check in the future for newer version.
