### ISSUE TITLE
Observe one problem about small number of genes case

### ISSUE THREAD

**Issue by HelloWorldLTY** [bowang-lab/scGPT#99]
Hi, I find that for some datasets, if we set the max_seq_len as a relatively small number, for example, 200 (comparing with 2000), we will face a bug for the pre-processing step:

```
# set up the preprocessor, use the args to config the workflow
preprocessor = Preprocessor(
    use_key="X",  # the key in adata.layers to use as raw data
    filter_gene_by_counts=0,  # step 1
    filter_cell_by_counts=False,  # step 2
    normalize_total=1e4,  # 3. whether to normalize the raw data and to what sum
    result_normed_key="X_normed",  # the key in adata.layers to store the normalized data
    log1p=data_is_raw,  # 4. whether to log1p the normalized data
    result_log1p_key="X_log1p",
    subset_hvg=200,  # 5. whether to subset the raw data to highly variable genes
    hvg_flavor="seurat_v3" if data_is_raw else "cell_ranger",
    binning=n_bins,  # 6. whether to bin the raw data and to what number of bins
    result_binned_key="X_binned",  # the key in adata.layers to store the binned data
)
```

We will see a bug known as:
```
File /notebooks/scGPT/examples/../scgpt/preprocess.py:186, in Preprocessor.__call__(self, adata, batch_key)
    184 non_zero_ids = row.nonzero()
    185 non_zero_row = row[non_zero_ids]
--> 186 bins = np.quantile(non_zero_row, np.linspace(0, 1, n_bins - 1))
    187 # bins = np.sort(np.unique(bins))
    188 # NOTE: comment this line for now, since this will make the each category
    189 # has different relative meaning across datasets
    190 non_zero_digits = _digitize(non_zero_row, bins)

IndexError: cannot do a non-empty take from an empty axes.
```

I have tried three different datasets and observed this bug under all of the cases. The codes I used are from cell-type annotation step. Could you please help me investiage this problem? Thanks!

**Comment by CalmDownTR** [comment]
Hi, @HelloWorldLTY 
I have encountered the same problem as you, and for me, it is due to the occurrence of 0 rows in the expression matrix, which can lead to np.quantity errors. It may be caused by QC or HVG. After filtering out all cells with zero expression levels, I resolved this issue.

**Comment by subercui** [comment]
Hi, thanks for pointing this out. This is also related to #84. I updated the code in the new commit to handle the cells with all zeros and it will throw a warning. Please see the related code here

https://github.com/bowang-lab/scGPT/blob/dc8f3241e686f2869ddbba5966501b4e86c315fc/scgpt/preprocess.py#L187-L196
